# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phonebook.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'phonebook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fphonebook.proto\x12\tphonebook\"Y\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\"W\n\x0e\x43ontactRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cphone_number\x18\x02 \x01(\t\x12#\n\x07\x63ontact\x18\x03 \x01(\x0b\x32\x12.phonebook.Contact\"X\n\x0f\x43ontactResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x07\x63ontact\x18\x03 \x01(\x0b\x32\x12.phonebook.Contact\"B\n\x0b\x43ontactList\x12$\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x12.phonebook.Contact\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2\xe6\x02\n\x10PhonebookService\x12\x43\n\nAddContact\x12\x19.phonebook.ContactRequest\x1a\x1a.phonebook.ContactResponse\x12\x43\n\nGetContact\x12\x19.phonebook.ContactRequest\x1a\x1a.phonebook.ContactResponse\x12\x46\n\rUpdateContact\x12\x19.phonebook.ContactRequest\x1a\x1a.phonebook.ContactResponse\x12\x46\n\rDeleteContact\x12\x19.phonebook.ContactRequest\x1a\x1a.phonebook.ContactResponse\x12\x38\n\x0cListContacts\x12\x10.phonebook.Empty\x1a\x16.phonebook.ContactListB-\n\x19\x63om.distributed.phonebookB\x0ePhonebookProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phonebook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.distributed.phonebookB\016PhonebookProtoP\001'
  _globals['_CONTACT']._serialized_start=30
  _globals['_CONTACT']._serialized_end=119
  _globals['_CONTACTREQUEST']._serialized_start=121
  _globals['_CONTACTREQUEST']._serialized_end=208
  _globals['_CONTACTRESPONSE']._serialized_start=210
  _globals['_CONTACTRESPONSE']._serialized_end=298
  _globals['_CONTACTLIST']._serialized_start=300
  _globals['_CONTACTLIST']._serialized_end=366
  _globals['_EMPTY']._serialized_start=368
  _globals['_EMPTY']._serialized_end=375
  _globals['_PHONEBOOKSERVICE']._serialized_start=378
  _globals['_PHONEBOOKSERVICE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
